package com.neu.mapper;

import com.neu.entity.ConstantItem;
import com.neu.entity.ConstantItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstantItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    long countByExample(ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int deleteByExample(ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int insert(ConstantItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int insertSelective(ConstantItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    List<ConstantItem> selectByExample(ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    ConstantItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConstantItem record, @Param("example") ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConstantItem record, @Param("example") ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConstantItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constantitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConstantItem record);
}