package com.neu.mapper;

import com.neu.entity.ConstantType;
import com.neu.entity.ConstantTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstantTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    long countByExample(ConstantTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int deleteByExample(ConstantTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int insert(ConstantType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int insertSelective(ConstantType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    List<ConstantType> selectByExample(ConstantTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    ConstantType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConstantType record, @Param("example") ConstantTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConstantType record, @Param("example") ConstantTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConstantType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConstantType record);
}