package com.neu.mapper;

import com.neu.entity.Scheduling;
import com.neu.entity.SchedulingExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SchedulingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    long countByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int deleteByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int insert(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int insertSelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    List<Scheduling> selectByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    Scheduling selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Scheduling record, @Param("example") SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Scheduling record, @Param("example") SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Scheduling record);
    
    List<Map<String, Object>> getDocList(Map<String, Object> params);
}