package com.neu.mapper;

import com.neu.entity.SettleCategory;
import com.neu.entity.SettleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SettleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    long countByExample(SettleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int deleteByExample(SettleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int insert(SettleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int insertSelective(SettleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    List<SettleCategory> selectByExample(SettleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    SettleCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SettleCategory record, @Param("example") SettleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SettleCategory record, @Param("example") SettleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SettleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SettleCategory record);
}