package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table constantitem
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ConstantItem {
    /**
     * Database Column Remarks:
     *   ID主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属常数类别ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ConstantTypeID
     *
     * @mbg.generated
     */
    private ConstantType constantType;

    /**
     * Database Column Remarks:
     *   常数项编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ConstantCode
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   常数项名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ConstantName
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.DelMark
     *
     * @mbg.generated
     */
    private Integer delMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ID
     *
     * @return the value of constantitem.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ID
     *
     * @param id the value for constantitem.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ConstantTypeID
     *
     * @return the value of constantitem.ConstantTypeID
     *
     * @mbg.generated
     */
    public ConstantType getConstantType() {
        return constantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ConstantTypeID
     *
     * @param constantType the value for constantitem.ConstantTypeID
     *
     * @mbg.generated
     */
    public void setConstantType(ConstantType constantType) {
        this.constantType = constantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ConstantCode
     *
     * @return the value of constantitem.ConstantCode
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ConstantCode
     *
     * @param code the value for constantitem.ConstantCode
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ConstantName
     *
     * @return the value of constantitem.ConstantName
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ConstantName
     *
     * @param name the value for constantitem.ConstantName
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.DelMark
     *
     * @return the value of constantitem.DelMark
     *
     * @mbg.generated
     */
    public Integer getDelMark() {
        return delMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.DelMark
     *
     * @param delMark the value for constantitem.DelMark
     *
     * @mbg.generated
     */
    public void setDelMark(Integer delMark) {
        this.delMark = delMark;
    }
}