package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table constanttype
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ConstantType {
    /**
     * Database Column Remarks:
     *   ID主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   常数类别编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.ConstantTypeCode
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   常数类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.ConstantTypeName
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.DelMark
     *
     * @mbg.generated
     */
    private Integer delMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.ID
     *
     * @return the value of constanttype.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.ID
     *
     * @param id the value for constanttype.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.ConstantTypeCode
     *
     * @return the value of constanttype.ConstantTypeCode
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.ConstantTypeCode
     *
     * @param code the value for constanttype.ConstantTypeCode
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.ConstantTypeName
     *
     * @return the value of constanttype.ConstantTypeName
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.ConstantTypeName
     *
     * @param name the value for constanttype.ConstantTypeName
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.DelMark
     *
     * @return the value of constanttype.DelMark
     *
     * @mbg.generated
     */
    public Integer getDelMark() {
        return delMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.DelMark
     *
     * @param delMark the value for constanttype.DelMark
     *
     * @mbg.generated
     */
    public void setDelMark(Integer delMark) {
        this.delMark = delMark;
    }
}