package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table department
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Department {
    /**
     * Database Column Remarks:
     *   ID主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   科室编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DeptCode
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   科室名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DeptName
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   科室分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DeptCategoryID
     *
     * @mbg.generated
     */
    private ConstantItem deptCategory;

    /**
     * Database Column Remarks:
     *   科室类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DeptType
     *
     * @mbg.generated
     */
    private Integer deptType;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DelMark
     *
     * @mbg.generated
     */
    private Integer delMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.ID
     *
     * @return the value of department.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.ID
     *
     * @param id the value for department.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptCode
     *
     * @return the value of department.DeptCode
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptCode
     *
     * @param code the value for department.DeptCode
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptName
     *
     * @return the value of department.DeptName
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /*@Override
	public String toString() {
		return "Department [id=" + id + ", code=" + code + ", name=" + name + ", deptCategory=" + deptCategory
				+ ", deptType=" + deptType + ", delMark=" + delMark + "]";
	}*/

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptName
     *
     * @param name the value for department.DeptName
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptCategoryID
     *
     * @return the value of department.DeptCategoryID
     *
     * @mbg.generated
     */
    public ConstantItem getDeptCategory() {
        return deptCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptCategoryID
     *
     * @param deptCategory the value for department.DeptCategoryID
     *
     * @mbg.generated
     */
    public void setDeptCategory(ConstantItem deptCategory) {
        this.deptCategory = deptCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptType
     *
     * @return the value of department.DeptType
     *
     * @mbg.generated
     */
    public Integer getDeptType() {
        return deptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptType
     *
     * @param deptType the value for department.DeptType
     *
     * @mbg.generated
     */
    public void setDeptType(Integer deptType) {
        this.deptType = deptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DelMark
     *
     * @return the value of department.DelMark
     *
     * @mbg.generated
     */
    public Integer getDelMark() {
        return delMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DelMark
     *
     * @param delMark the value for department.DelMark
     *
     * @mbg.generated
     */
    public void setDelMark(Integer delMark) {
        this.delMark = delMark;
    }
}