package com.neu.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table register
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Register {

	/**
	 * Database Column Remarks: ID主键 This field was generated by MyBatis Generator. This field corresponds to the database column register.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 病历号 This field was generated by MyBatis Generator. This field corresponds to the database column register.CaseNumber
	 * @mbg.generated
	 */
	private String caseNumber;
	/**
	 * Database Column Remarks: 姓名 This field was generated by MyBatis Generator. This field corresponds to the database column register.RealName
	 * @mbg.generated
	 */
	private String realname;
	/**
	 * Database Column Remarks: 性别 This field was generated by MyBatis Generator. This field corresponds to the database column register.Gender
	 * @mbg.generated
	 */
	private Integer gender;
	/**
	 * Database Column Remarks: 身份证号 This field was generated by MyBatis Generator. This field corresponds to the database column register.IDnumber
	 * @mbg.generated
	 */
	private String idNumber;
	/**
	 * Database Column Remarks: 出生日期 This field was generated by MyBatis Generator. This field corresponds to the database column register.BirthDate
	 * @mbg.generated
	 */
	private Date birthDate;
	/**
	 * Database Column Remarks: 年龄 This field was generated by MyBatis Generator. This field corresponds to the database column register.Age
	 * @mbg.generated
	 */
	private Integer Age;
	/**
	 * Database Column Remarks: 年龄类型 岁 月 天 This field was generated by MyBatis Generator. This field corresponds to the database column register.AgeType
	 * @mbg.generated
	 */
	private String ageType;
	/**
	 * Database Column Remarks: 家庭住址 This field was generated by MyBatis Generator. This field corresponds to the database column register.HomeAddress
	 * @mbg.generated
	 */
	private String homeAddress;
	/**
	 * Database Column Remarks: 本次看诊日期 This field was generated by MyBatis Generator. This field corresponds to the database column register.VisitDate
	 * @mbg.generated
	 */
	private Date visitDate;
	/**
	 * Database Column Remarks: 午别  上午/下午 This field was generated by MyBatis Generator. This field corresponds to the database column register.Noon
	 * @mbg.generated
	 */
	private String noon;
	/**
	 * Database Column Remarks: 本次挂号科室ID This field was generated by MyBatis Generator. This field corresponds to the database column register.DeptID
	 * @mbg.generated
	 */
	private Department dept;
	/**
	 * Database Column Remarks: 本次挂号医生ID This field was generated by MyBatis Generator. This field corresponds to the database column register.UserID
	 * @mbg.generated
	 */
	private Integer userID;
	/**
	 * Database Column Remarks: 本次挂号级别ID This field was generated by MyBatis Generator. This field corresponds to the database column register.RegistLeID
	 * @mbg.generated
	 */
	private Integer registLeID;
	/**
	 * Database Column Remarks: 结算类别ID This field was generated by MyBatis Generator. This field corresponds to the database column register.SettleID
	 * @mbg.generated
	 */
	private Integer settleID;
	/**
	 * Database Column Remarks: 病历本要否  是/否 This field was generated by MyBatis Generator. This field corresponds to the database column register.IsBook
	 * @mbg.generated
	 */
	private String isBook;
	/**
	 * Database Column Remarks: 挂号时间 This field was generated by MyBatis Generator. This field corresponds to the database column register.RegistTime
	 * @mbg.generated
	 */
	private Date registTime;
	/**
	 * Database Column Remarks: 挂号员ID This field was generated by MyBatis Generator. This field corresponds to the database column register.RegisterID
	 * @mbg.generated
	 */
	private Integer registerID;
	/**
	 * Database Column Remarks: 本次看诊状态 This field was generated by MyBatis Generator. This field corresponds to the database column register.VisitState
	 * @mbg.generated
	 */
	private Integer visitState;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.ID
	 * @return  the value of register.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.ID
	 * @param id  the value for register.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.CaseNumber
	 * @return  the value of register.CaseNumber
	 * @mbg.generated
	 */
	public String getCaseNumber() {
		return caseNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.CaseNumber
	 * @param caseNumber  the value for register.CaseNumber
	 * @mbg.generated
	 */
	public void setCaseNumber(String caseNumber) {
		this.caseNumber = caseNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.RealName
	 * @return  the value of register.RealName
	 * @mbg.generated
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.RealName
	 * @param realname  the value for register.RealName
	 * @mbg.generated
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.Gender
	 * @return  the value of register.Gender
	 * @mbg.generated
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.Gender
	 * @param gender  the value for register.Gender
	 * @mbg.generated
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.IDnumber
	 * @return  the value of register.IDnumber
	 * @mbg.generated
	 */
	public String getIdNumber() {
		return idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.IDnumber
	 * @param idNumber  the value for register.IDnumber
	 * @mbg.generated
	 */
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.BirthDate
	 * @return  the value of register.BirthDate
	 * @mbg.generated
	 */
	public Date getBirthDate() {
		return birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.BirthDate
	 * @param birthDate  the value for register.BirthDate
	 * @mbg.generated
	 */
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.Age
	 * @return  the value of register.Age
	 * @mbg.generated
	 */
	public Integer getAge() {
		return Age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.Age
	 * @param Age  the value for register.Age
	 * @mbg.generated
	 */
	public void setAge(Integer Age) {
		this.Age = Age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.AgeType
	 * @return  the value of register.AgeType
	 * @mbg.generated
	 */
	public String getAgeType() {
		return ageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.AgeType
	 * @param ageType  the value for register.AgeType
	 * @mbg.generated
	 */
	public void setAgeType(String ageType) {
		this.ageType = ageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.HomeAddress
	 * @return  the value of register.HomeAddress
	 * @mbg.generated
	 */
	public String getHomeAddress() {
		return homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.HomeAddress
	 * @param homeAddress  the value for register.HomeAddress
	 * @mbg.generated
	 */
	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.VisitDate
	 * @return  the value of register.VisitDate
	 * @mbg.generated
	 */
	public Date getVisitDate() {
		return visitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.VisitDate
	 * @param visitDate  the value for register.VisitDate
	 * @mbg.generated
	 */
	public void setVisitDate(Date visitDate) {
		this.visitDate = visitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.Noon
	 * @return  the value of register.Noon
	 * @mbg.generated
	 */
	public String getNoon() {
		return noon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.Noon
	 * @param noon  the value for register.Noon
	 * @mbg.generated
	 */
	public void setNoon(String noon) {
		this.noon = noon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.DeptID
	 * @return  the value of register.DeptID
	 * @mbg.generated
	 */
	public Department getDept() {
		return dept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.DeptID
	 * @param dept  the value for register.DeptID
	 * @mbg.generated
	 */
	public void setDept(Department dept) {
		this.dept = dept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.UserID
	 * @return  the value of register.UserID
	 * @mbg.generated
	 */
	public Integer getUserID() {
		return userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.UserID
	 * @param userID  the value for register.UserID
	 * @mbg.generated
	 */
	public void setUserID(Integer userID) {
		this.userID = userID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.RegistLeID
	 * @return  the value of register.RegistLeID
	 * @mbg.generated
	 */
	public Integer getRegistLeID() {
		return registLeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.RegistLeID
	 * @param registLeID  the value for register.RegistLeID
	 * @mbg.generated
	 */
	public void setRegistLeID(Integer registLeID) {
		this.registLeID = registLeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.SettleID
	 * @return  the value of register.SettleID
	 * @mbg.generated
	 */
	public Integer getSettleID() {
		return settleID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.SettleID
	 * @param settleID  the value for register.SettleID
	 * @mbg.generated
	 */
	public void setSettleID(Integer settleID) {
		this.settleID = settleID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.IsBook
	 * @return  the value of register.IsBook
	 * @mbg.generated
	 */
	public String getIsBook() {
		return isBook;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.IsBook
	 * @param isBook  the value for register.IsBook
	 * @mbg.generated
	 */
	public void setIsBook(String isBook) {
		this.isBook = isBook;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.RegistTime
	 * @return  the value of register.RegistTime
	 * @mbg.generated
	 */
	public Date getRegistTime() {
		return registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.RegistTime
	 * @param registTime  the value for register.RegistTime
	 * @mbg.generated
	 */
	public void setRegistTime(Date registTime) {
		this.registTime = registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.RegisterID
	 * @return  the value of register.RegisterID
	 * @mbg.generated
	 */
	public Integer getRegisterID() {
		return registerID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.RegisterID
	 * @param registerID  the value for register.RegisterID
	 * @mbg.generated
	 */
	public void setRegisterID(Integer registerID) {
		this.registerID = registerID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column register.VisitState
	 * @return  the value of register.VisitState
	 * @mbg.generated
	 */
	public Integer getVisitState() {
		return visitState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column register.VisitState
	 * @param visitState  the value for register.VisitState
	 * @mbg.generated
	 */
	public void setVisitState(Integer visitState) {
		this.visitState = visitState;
	}
}