package com.neu.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RegisterExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table register
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table register
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table register
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public RegisterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table register
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table register
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseNumberIsNull() {
			addCriterion("CaseNumber is null");
			return (Criteria) this;
		}

		public Criteria andCaseNumberIsNotNull() {
			addCriterion("CaseNumber is not null");
			return (Criteria) this;
		}

		public Criteria andCaseNumberEqualTo(String value) {
			addCriterion("CaseNumber =", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberNotEqualTo(String value) {
			addCriterion("CaseNumber <>", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberGreaterThan(String value) {
			addCriterion("CaseNumber >", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberGreaterThanOrEqualTo(String value) {
			addCriterion("CaseNumber >=", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberLessThan(String value) {
			addCriterion("CaseNumber <", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberLessThanOrEqualTo(String value) {
			addCriterion("CaseNumber <=", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberLike(String value) {
			addCriterion("CaseNumber like", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberNotLike(String value) {
			addCriterion("CaseNumber not like", value, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberIn(List<String> values) {
			addCriterion("CaseNumber in", values, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberNotIn(List<String> values) {
			addCriterion("CaseNumber not in", values, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberBetween(String value1, String value2) {
			addCriterion("CaseNumber between", value1, value2, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andCaseNumberNotBetween(String value1, String value2) {
			addCriterion("CaseNumber not between", value1, value2, "caseNumber");
			return (Criteria) this;
		}

		public Criteria andRealnameIsNull() {
			addCriterion("RealName is null");
			return (Criteria) this;
		}

		public Criteria andRealnameIsNotNull() {
			addCriterion("RealName is not null");
			return (Criteria) this;
		}

		public Criteria andRealnameEqualTo(String value) {
			addCriterion("RealName =", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotEqualTo(String value) {
			addCriterion("RealName <>", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameGreaterThan(String value) {
			addCriterion("RealName >", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameGreaterThanOrEqualTo(String value) {
			addCriterion("RealName >=", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameLessThan(String value) {
			addCriterion("RealName <", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameLessThanOrEqualTo(String value) {
			addCriterion("RealName <=", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameLike(String value) {
			addCriterion("RealName like", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotLike(String value) {
			addCriterion("RealName not like", value, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameIn(List<String> values) {
			addCriterion("RealName in", values, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotIn(List<String> values) {
			addCriterion("RealName not in", values, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameBetween(String value1, String value2) {
			addCriterion("RealName between", value1, value2, "realname");
			return (Criteria) this;
		}

		public Criteria andRealnameNotBetween(String value1, String value2) {
			addCriterion("RealName not between", value1, value2, "realname");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("Gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("Gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Integer value) {
			addCriterion("Gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Integer value) {
			addCriterion("Gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Integer value) {
			addCriterion("Gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
			addCriterion("Gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Integer value) {
			addCriterion("Gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Integer value) {
			addCriterion("Gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Integer> values) {
			addCriterion("Gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Integer> values) {
			addCriterion("Gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Integer value1, Integer value2) {
			addCriterion("Gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Integer value1, Integer value2) {
			addCriterion("Gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andIdNumberIsNull() {
			addCriterion("IDnumber is null");
			return (Criteria) this;
		}

		public Criteria andIdNumberIsNotNull() {
			addCriterion("IDnumber is not null");
			return (Criteria) this;
		}

		public Criteria andIdNumberEqualTo(String value) {
			addCriterion("IDnumber =", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotEqualTo(String value) {
			addCriterion("IDnumber <>", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberGreaterThan(String value) {
			addCriterion("IDnumber >", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
			addCriterion("IDnumber >=", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberLessThan(String value) {
			addCriterion("IDnumber <", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberLessThanOrEqualTo(String value) {
			addCriterion("IDnumber <=", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberLike(String value) {
			addCriterion("IDnumber like", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotLike(String value) {
			addCriterion("IDnumber not like", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberIn(List<String> values) {
			addCriterion("IDnumber in", values, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotIn(List<String> values) {
			addCriterion("IDnumber not in", values, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberBetween(String value1, String value2) {
			addCriterion("IDnumber between", value1, value2, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotBetween(String value1, String value2) {
			addCriterion("IDnumber not between", value1, value2, "idNumber");
			return (Criteria) this;
		}

		public Criteria andBirthDateIsNull() {
			addCriterion("BirthDate is null");
			return (Criteria) this;
		}

		public Criteria andBirthDateIsNotNull() {
			addCriterion("BirthDate is not null");
			return (Criteria) this;
		}

		public Criteria andBirthDateEqualTo(Date value) {
			addCriterionForJDBCDate("BirthDate =", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("BirthDate <>", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateGreaterThan(Date value) {
			addCriterionForJDBCDate("BirthDate >", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("BirthDate >=", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateLessThan(Date value) {
			addCriterionForJDBCDate("BirthDate <", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("BirthDate <=", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateIn(List<Date> values) {
			addCriterionForJDBCDate("BirthDate in", values, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("BirthDate not in", values, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("BirthDate between", value1, value2, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("BirthDate not between", value1, value2, "birthDate");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("Age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("Age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(Integer value) {
			addCriterion("Age =", value, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(Integer value) {
			addCriterion("Age <>", value, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(Integer value) {
			addCriterion("Age >", value, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
			addCriterion("Age >=", value, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(Integer value) {
			addCriterion("Age <", value, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(Integer value) {
			addCriterion("Age <=", value, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<Integer> values) {
			addCriterion("Age in", values, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<Integer> values) {
			addCriterion("Age not in", values, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(Integer value1, Integer value2) {
			addCriterion("Age between", value1, value2, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(Integer value1, Integer value2) {
			addCriterion("Age not between", value1, value2, "Age");
			return (Criteria) this;
		}

		public Criteria andAgeTypeIsNull() {
			addCriterion("AgeType is null");
			return (Criteria) this;
		}

		public Criteria andAgeTypeIsNotNull() {
			addCriterion("AgeType is not null");
			return (Criteria) this;
		}

		public Criteria andAgeTypeEqualTo(String value) {
			addCriterion("AgeType =", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeNotEqualTo(String value) {
			addCriterion("AgeType <>", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeGreaterThan(String value) {
			addCriterion("AgeType >", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeGreaterThanOrEqualTo(String value) {
			addCriterion("AgeType >=", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeLessThan(String value) {
			addCriterion("AgeType <", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeLessThanOrEqualTo(String value) {
			addCriterion("AgeType <=", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeLike(String value) {
			addCriterion("AgeType like", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeNotLike(String value) {
			addCriterion("AgeType not like", value, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeIn(List<String> values) {
			addCriterion("AgeType in", values, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeNotIn(List<String> values) {
			addCriterion("AgeType not in", values, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeBetween(String value1, String value2) {
			addCriterion("AgeType between", value1, value2, "ageType");
			return (Criteria) this;
		}

		public Criteria andAgeTypeNotBetween(String value1, String value2) {
			addCriterion("AgeType not between", value1, value2, "ageType");
			return (Criteria) this;
		}

		public Criteria andHomeAddressIsNull() {
			addCriterion("HomeAddress is null");
			return (Criteria) this;
		}

		public Criteria andHomeAddressIsNotNull() {
			addCriterion("HomeAddress is not null");
			return (Criteria) this;
		}

		public Criteria andHomeAddressEqualTo(String value) {
			addCriterion("HomeAddress =", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressNotEqualTo(String value) {
			addCriterion("HomeAddress <>", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressGreaterThan(String value) {
			addCriterion("HomeAddress >", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressGreaterThanOrEqualTo(String value) {
			addCriterion("HomeAddress >=", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressLessThan(String value) {
			addCriterion("HomeAddress <", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressLessThanOrEqualTo(String value) {
			addCriterion("HomeAddress <=", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressLike(String value) {
			addCriterion("HomeAddress like", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressNotLike(String value) {
			addCriterion("HomeAddress not like", value, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressIn(List<String> values) {
			addCriterion("HomeAddress in", values, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressNotIn(List<String> values) {
			addCriterion("HomeAddress not in", values, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressBetween(String value1, String value2) {
			addCriterion("HomeAddress between", value1, value2, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andHomeAddressNotBetween(String value1, String value2) {
			addCriterion("HomeAddress not between", value1, value2, "homeAddress");
			return (Criteria) this;
		}

		public Criteria andVisitDateIsNull() {
			addCriterion("VisitDate is null");
			return (Criteria) this;
		}

		public Criteria andVisitDateIsNotNull() {
			addCriterion("VisitDate is not null");
			return (Criteria) this;
		}

		public Criteria andVisitDateEqualTo(Date value) {
			addCriterionForJDBCDate("VisitDate =", value, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("VisitDate <>", value, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateGreaterThan(Date value) {
			addCriterionForJDBCDate("VisitDate >", value, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("VisitDate >=", value, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateLessThan(Date value) {
			addCriterionForJDBCDate("VisitDate <", value, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("VisitDate <=", value, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateIn(List<Date> values) {
			addCriterionForJDBCDate("VisitDate in", values, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("VisitDate not in", values, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("VisitDate between", value1, value2, "visitDate");
			return (Criteria) this;
		}

		public Criteria andVisitDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("VisitDate not between", value1, value2, "visitDate");
			return (Criteria) this;
		}

		public Criteria andNoonIsNull() {
			addCriterion("Noon is null");
			return (Criteria) this;
		}

		public Criteria andNoonIsNotNull() {
			addCriterion("Noon is not null");
			return (Criteria) this;
		}

		public Criteria andNoonEqualTo(String value) {
			addCriterion("Noon =", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonNotEqualTo(String value) {
			addCriterion("Noon <>", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonGreaterThan(String value) {
			addCriterion("Noon >", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonGreaterThanOrEqualTo(String value) {
			addCriterion("Noon >=", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonLessThan(String value) {
			addCriterion("Noon <", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonLessThanOrEqualTo(String value) {
			addCriterion("Noon <=", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonLike(String value) {
			addCriterion("Noon like", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonNotLike(String value) {
			addCriterion("Noon not like", value, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonIn(List<String> values) {
			addCriterion("Noon in", values, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonNotIn(List<String> values) {
			addCriterion("Noon not in", values, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonBetween(String value1, String value2) {
			addCriterion("Noon between", value1, value2, "noon");
			return (Criteria) this;
		}

		public Criteria andNoonNotBetween(String value1, String value2) {
			addCriterion("Noon not between", value1, value2, "noon");
			return (Criteria) this;
		}

		public Criteria andDeptIsNull() {
			addCriterion("DeptID is null");
			return (Criteria) this;
		}

		public Criteria andDeptIsNotNull() {
			addCriterion("DeptID is not null");
			return (Criteria) this;
		}

		public Criteria andDeptEqualTo(Department value) {
			addCriterion("DeptID =", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptNotEqualTo(Department value) {
			addCriterion("DeptID <>", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptGreaterThan(Department value) {
			addCriterion("DeptID >", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptGreaterThanOrEqualTo(Department value) {
			addCriterion("DeptID >=", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptLessThan(Department value) {
			addCriterion("DeptID <", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptLessThanOrEqualTo(Department value) {
			addCriterion("DeptID <=", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptIn(List<Department> values) {
			addCriterion("DeptID in", values, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptNotIn(List<Department> values) {
			addCriterion("DeptID not in", values, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptBetween(Department value1, Department value2) {
			addCriterion("DeptID between", value1, value2, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptNotBetween(Department value1, Department value2) {
			addCriterion("DeptID not between", value1, value2, "dept");
			return (Criteria) this;
		}

		public Criteria andUserIDIsNull() {
			addCriterion("UserID is null");
			return (Criteria) this;
		}

		public Criteria andUserIDIsNotNull() {
			addCriterion("UserID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIDEqualTo(Integer value) {
			addCriterion("UserID =", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotEqualTo(Integer value) {
			addCriterion("UserID <>", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDGreaterThan(Integer value) {
			addCriterion("UserID >", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDGreaterThanOrEqualTo(Integer value) {
			addCriterion("UserID >=", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLessThan(Integer value) {
			addCriterion("UserID <", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDLessThanOrEqualTo(Integer value) {
			addCriterion("UserID <=", value, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDIn(List<Integer> values) {
			addCriterion("UserID in", values, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotIn(List<Integer> values) {
			addCriterion("UserID not in", values, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDBetween(Integer value1, Integer value2) {
			addCriterion("UserID between", value1, value2, "userID");
			return (Criteria) this;
		}

		public Criteria andUserIDNotBetween(Integer value1, Integer value2) {
			addCriterion("UserID not between", value1, value2, "userID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDIsNull() {
			addCriterion("RegistLeID is null");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDIsNotNull() {
			addCriterion("RegistLeID is not null");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDEqualTo(Integer value) {
			addCriterion("RegistLeID =", value, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDNotEqualTo(Integer value) {
			addCriterion("RegistLeID <>", value, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDGreaterThan(Integer value) {
			addCriterion("RegistLeID >", value, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDGreaterThanOrEqualTo(Integer value) {
			addCriterion("RegistLeID >=", value, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDLessThan(Integer value) {
			addCriterion("RegistLeID <", value, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDLessThanOrEqualTo(Integer value) {
			addCriterion("RegistLeID <=", value, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDIn(List<Integer> values) {
			addCriterion("RegistLeID in", values, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDNotIn(List<Integer> values) {
			addCriterion("RegistLeID not in", values, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDBetween(Integer value1, Integer value2) {
			addCriterion("RegistLeID between", value1, value2, "registLeID");
			return (Criteria) this;
		}

		public Criteria andRegistLeIDNotBetween(Integer value1, Integer value2) {
			addCriterion("RegistLeID not between", value1, value2, "registLeID");
			return (Criteria) this;
		}

		public Criteria andSettleIDIsNull() {
			addCriterion("SettleID is null");
			return (Criteria) this;
		}

		public Criteria andSettleIDIsNotNull() {
			addCriterion("SettleID is not null");
			return (Criteria) this;
		}

		public Criteria andSettleIDEqualTo(Integer value) {
			addCriterion("SettleID =", value, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDNotEqualTo(Integer value) {
			addCriterion("SettleID <>", value, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDGreaterThan(Integer value) {
			addCriterion("SettleID >", value, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDGreaterThanOrEqualTo(Integer value) {
			addCriterion("SettleID >=", value, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDLessThan(Integer value) {
			addCriterion("SettleID <", value, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDLessThanOrEqualTo(Integer value) {
			addCriterion("SettleID <=", value, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDIn(List<Integer> values) {
			addCriterion("SettleID in", values, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDNotIn(List<Integer> values) {
			addCriterion("SettleID not in", values, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDBetween(Integer value1, Integer value2) {
			addCriterion("SettleID between", value1, value2, "settleID");
			return (Criteria) this;
		}

		public Criteria andSettleIDNotBetween(Integer value1, Integer value2) {
			addCriterion("SettleID not between", value1, value2, "settleID");
			return (Criteria) this;
		}

		public Criteria andIsBookIsNull() {
			addCriterion("IsBook is null");
			return (Criteria) this;
		}

		public Criteria andIsBookIsNotNull() {
			addCriterion("IsBook is not null");
			return (Criteria) this;
		}

		public Criteria andIsBookEqualTo(String value) {
			addCriterion("IsBook =", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookNotEqualTo(String value) {
			addCriterion("IsBook <>", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookGreaterThan(String value) {
			addCriterion("IsBook >", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookGreaterThanOrEqualTo(String value) {
			addCriterion("IsBook >=", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookLessThan(String value) {
			addCriterion("IsBook <", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookLessThanOrEqualTo(String value) {
			addCriterion("IsBook <=", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookLike(String value) {
			addCriterion("IsBook like", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookNotLike(String value) {
			addCriterion("IsBook not like", value, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookIn(List<String> values) {
			addCriterion("IsBook in", values, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookNotIn(List<String> values) {
			addCriterion("IsBook not in", values, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookBetween(String value1, String value2) {
			addCriterion("IsBook between", value1, value2, "isBook");
			return (Criteria) this;
		}

		public Criteria andIsBookNotBetween(String value1, String value2) {
			addCriterion("IsBook not between", value1, value2, "isBook");
			return (Criteria) this;
		}

		public Criteria andRegistTimeIsNull() {
			addCriterion("RegistTime is null");
			return (Criteria) this;
		}

		public Criteria andRegistTimeIsNotNull() {
			addCriterion("RegistTime is not null");
			return (Criteria) this;
		}

		public Criteria andRegistTimeEqualTo(Date value) {
			addCriterion("RegistTime =", value, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeNotEqualTo(Date value) {
			addCriterion("RegistTime <>", value, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeGreaterThan(Date value) {
			addCriterion("RegistTime >", value, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("RegistTime >=", value, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeLessThan(Date value) {
			addCriterion("RegistTime <", value, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeLessThanOrEqualTo(Date value) {
			addCriterion("RegistTime <=", value, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeIn(List<Date> values) {
			addCriterion("RegistTime in", values, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeNotIn(List<Date> values) {
			addCriterion("RegistTime not in", values, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeBetween(Date value1, Date value2) {
			addCriterion("RegistTime between", value1, value2, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegistTimeNotBetween(Date value1, Date value2) {
			addCriterion("RegistTime not between", value1, value2, "registTime");
			return (Criteria) this;
		}

		public Criteria andRegisterIDIsNull() {
			addCriterion("RegisterID is null");
			return (Criteria) this;
		}

		public Criteria andRegisterIDIsNotNull() {
			addCriterion("RegisterID is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterIDEqualTo(Integer value) {
			addCriterion("RegisterID =", value, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDNotEqualTo(Integer value) {
			addCriterion("RegisterID <>", value, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDGreaterThan(Integer value) {
			addCriterion("RegisterID >", value, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDGreaterThanOrEqualTo(Integer value) {
			addCriterion("RegisterID >=", value, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDLessThan(Integer value) {
			addCriterion("RegisterID <", value, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDLessThanOrEqualTo(Integer value) {
			addCriterion("RegisterID <=", value, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDIn(List<Integer> values) {
			addCriterion("RegisterID in", values, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDNotIn(List<Integer> values) {
			addCriterion("RegisterID not in", values, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDBetween(Integer value1, Integer value2) {
			addCriterion("RegisterID between", value1, value2, "registerID");
			return (Criteria) this;
		}

		public Criteria andRegisterIDNotBetween(Integer value1, Integer value2) {
			addCriterion("RegisterID not between", value1, value2, "registerID");
			return (Criteria) this;
		}

		public Criteria andVisitStateIsNull() {
			addCriterion("VisitState is null");
			return (Criteria) this;
		}

		public Criteria andVisitStateIsNotNull() {
			addCriterion("VisitState is not null");
			return (Criteria) this;
		}

		public Criteria andVisitStateEqualTo(Integer value) {
			addCriterion("VisitState =", value, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateNotEqualTo(Integer value) {
			addCriterion("VisitState <>", value, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateGreaterThan(Integer value) {
			addCriterion("VisitState >", value, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("VisitState >=", value, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateLessThan(Integer value) {
			addCriterion("VisitState <", value, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateLessThanOrEqualTo(Integer value) {
			addCriterion("VisitState <=", value, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateIn(List<Integer> values) {
			addCriterion("VisitState in", values, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateNotIn(List<Integer> values) {
			addCriterion("VisitState not in", values, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateBetween(Integer value1, Integer value2) {
			addCriterion("VisitState between", value1, value2, "visitState");
			return (Criteria) this;
		}

		public Criteria andVisitStateNotBetween(Integer value1, Integer value2) {
			addCriterion("VisitState not between", value1, value2, "visitState");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table register
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table register
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}