package com.neu.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table scheduling
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Scheduling {
    /**
     * Database Column Remarks:
     *   ID主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   排班日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.SchedDate
     *
     * @mbg.generated
     */
    private Date schedDate;

    /**
     * Database Column Remarks:
     *   科室ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.DeptID
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     * Database Column Remarks:
     *   医生ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.UserID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   午别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.Noon
     *
     * @mbg.generated
     */
    private String noon;

    /**
     * Database Column Remarks:
     *   排班规则ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.RuleID
     *
     * @mbg.generated
     */
    private Integer ruleID;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.DelMark
     *
     * @mbg.generated
     */
    private Integer delMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.ID
     *
     * @return the value of scheduling.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.ID
     *
     * @param id the value for scheduling.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.SchedDate
     *
     * @return the value of scheduling.SchedDate
     *
     * @mbg.generated
     */
    public Date getSchedDate() {
        return schedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.SchedDate
     *
     * @param schedDate the value for scheduling.SchedDate
     *
     * @mbg.generated
     */
    public void setSchedDate(Date schedDate) {
        this.schedDate = schedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.DeptID
     *
     * @return the value of scheduling.DeptID
     *
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.DeptID
     *
     * @param deptId the value for scheduling.DeptID
     *
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.UserID
     *
     * @return the value of scheduling.UserID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.UserID
     *
     * @param userId the value for scheduling.UserID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.Noon
     *
     * @return the value of scheduling.Noon
     *
     * @mbg.generated
     */
    public String getNoon() {
        return noon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.Noon
     *
     * @param noon the value for scheduling.Noon
     *
     * @mbg.generated
     */
    public void setNoon(String noon) {
        this.noon = noon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.RuleID
     *
     * @return the value of scheduling.RuleID
     *
     * @mbg.generated
     */
    public Integer getRuleID() {
        return ruleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.RuleID
     *
     * @param ruleID the value for scheduling.RuleID
     *
     * @mbg.generated
     */
    public void setRuleID(Integer ruleID) {
        this.ruleID = ruleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.DelMark
     *
     * @return the value of scheduling.DelMark
     *
     * @mbg.generated
     */
    public Integer getDelMark() {
        return delMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.DelMark
     *
     * @param delMark the value for scheduling.DelMark
     *
     * @mbg.generated
     */
    public void setDelMark(Integer delMark) {
        this.delMark = delMark;
    }
}