package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table settlecategory
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SettleCategory {
    /**
     * Database Column Remarks:
     *   ID主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   类别编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.SettleCode
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.SettleName
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   显示顺序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.SequenceNo
     *
     * @mbg.generated
     */
    private Integer sequenceNo;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.DelMark
     *
     * @mbg.generated
     */
    private Integer delMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.ID
     *
     * @return the value of settlecategory.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.ID
     *
     * @param id the value for settlecategory.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SettleCode
     *
     * @return the value of settlecategory.SettleCode
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SettleCode
     *
     * @param code the value for settlecategory.SettleCode
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SettleName
     *
     * @return the value of settlecategory.SettleName
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SettleName
     *
     * @param name the value for settlecategory.SettleName
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SequenceNo
     *
     * @return the value of settlecategory.SequenceNo
     *
     * @mbg.generated
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SequenceNo
     *
     * @param sequenceNo the value for settlecategory.SequenceNo
     *
     * @mbg.generated
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.DelMark
     *
     * @return the value of settlecategory.DelMark
     *
     * @mbg.generated
     */
    public Integer getDelMark() {
        return delMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.DelMark
     *
     * @param delMark the value for settlecategory.DelMark
     *
     * @mbg.generated
     */
    public void setDelMark(Integer delMark) {
        this.delMark = delMark;
    }
}